#!/usr/bin/python


import os, random, time

def getForgeVersion():
  return "Minecraft Forge " + getMinecraftVersion()

def getMinecraftVersion():
  tofind = "fmlbuild.mcversion="
  for line in open("build.gradle"):
    if "FORGEMARK" in line:
      ret = line.split('"')[1].strip()
      return ret
  return "unknown"

def run(cmd, expect_exit_code=0):
  print "> ", cmd
  exit_code = os.system(cmd)
  if expect_exit_code != exit_code and expect_exit_code != None:
      print "> Exit code = ", exit_code
      if expect_exit_code != any: raise SystemExit(exit_code)

run("git submodule update --init --recursive")

open("src/main/resources/assets/factorization/lang/en_US.lang").close()

exp = os.path.expanduser

version = open("fzversion").read().strip()
mc_forge_version = getMinecraftVersion()
filename = "Factorization-{0}.jar".format(version)

run("./rungradle build deobfJar writeFzFile")

#Check for baddies
run("./check_norelease", expect_exit_code=any)

print("\n"*4)
LOG  = "Factorization " + version + "\n"
LOG += "Built on " + time.strftime("%F") + " against " + (getForgeVersion() + "\n")
print(LOG)
